[package]
name = "luxcontract"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]


[addresses]
veralux = "0x0"
StakingContract = "0x0"
TreasuryAddress = "0x0"
Authority1 = "0x0"
Authority2 = "0x0"
Authority3 = "0x0"
Authority4 = "0x0"
Authority5 = "0x0"
GovernanceAddress = "0x0"
LiquidityAddress = "0x0"
BurnAddress = "0x0"
PrivateSale = "0x0"
Presale = "0x0"
LiquidityPool = "0x0"
Airdrop = "0x0"
StakingRewards = "0x0"
Team = "0x0"
Marketing = "0x0"

[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"
