[package]
name = "luxcontract"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]


[addresses]
veralux = "0x1"
StakingContract = "0x2"
TreasuryAddress = "0x3"
Authority1 = "0x4"
Authority2 = "0x5"
Authority3 = "0x6"
Authority4 = "0x7"
Authority5 = "0x8"
GovernanceAddress = "0x9"
LiquidityAddress = "0xa"
BurnAddress = "0xb"
PrivateSale = "0xc"
Presale = "0xd"
LiquidityPool = "0xe"
Airdrop = "0xf"
StakingRewards = "0x10"
Team = "0x11"
Marketing = "0x12"

[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"
